// Real account data derived from ISC territory export + BTSS motion context

export const MOCK_ACCOUNTS = [
  {
    id: 'acc-001',
    name: 'UNILEVER',
    coverageId: 'T0018765',
    industry: 'Consumer Products',
    subIndustry: 'CP - Household / Health & Beauty',
    size: 'Enterprise',
    location: 'New York, NY',
    globalRevenue: 64881156000,
    ibmSpend: 502668,
    status: 'Active Opportunity',
    lastContact: '2025-06-12',
    installedBase: ['IBM Fusion'],
    intentScore: 78,
    iscNotes: 'CONOPCO INC subsidiary has existing IBM spend $502K. Potential to expand Fusion footprint into broader Unilever data fabric initiative. Champion TBD.',
  },
  {
    id: 'acc-002',
    name: 'CAMPBELL SOUP CO.',
    coverageId: 'T0018765',
    industry: 'Consumer Products',
    subIndustry: 'CP - Food Manufacturing',
    size: 'Enterprise',
    location: 'Camden, NJ',
    globalRevenue: 9636000000,
    ibmSpend: 9176517,
    status: 'Active Opportunity',
    lastContact: '2025-06-18',
    installedBase: ['IBM FlashSystem', 'IBM Fusion'],
    intentScore: 91,
    iscNotes: 'Strong IBM relationship — $9.1M spend 23-26. FlashSystem refresh conversation underway. WM Bolthouse Farms subsidiary also has active engagement ($33K). Procurement contact is Director of IT Infrastructure.',
  },
  {
    id: 'acc-003',
    name: 'CHURCH & DWIGHT CO INC',
    coverageId: 'T0018765',
    industry: 'Consumer Products',
    subIndustry: 'CP - Household / Health & Beauty',
    size: 'Enterprise',
    location: 'Ewing, NJ',
    globalRevenue: 6107100000,
    ibmSpend: 2011043,
    status: 'Active Opportunity',
    lastContact: '2025-06-20',
    installedBase: ['IBM PowerVS'],
    intentScore: 85,
    iscNotes: '$2M IBM spend. PowerVS engagement active. Opportunity to expand into FlashSystem for ERP storage. Key contact is VP of Enterprise Technology.',
  },
  {
    id: 'acc-004',
    name: 'CHANEL',
    coverageId: 'T0018765',
    industry: 'Consumer Products',
    subIndustry: 'CP - Household / Health & Beauty',
    size: 'Enterprise',
    location: 'New York, NY',
    globalRevenue: 5688707500,
    ibmSpend: 6864336,
    status: 'Active Opportunity',
    lastContact: '2025-06-15',
    installedBase: ['IBM FlashSystem', 'IBM Fusion'],
    intentScore: 94,
    iscNotes: '$6.8M IBM spend — one of the highest in territory. Active Fusion + FlashSystem footprint. Expansion opportunity tied to global digital transformation program. Executive sponsor engaged.',
  },
  {
    id: 'acc-005',
    name: 'BOOKING HOLDINGS',
    coverageId: 'T0018764',
    industry: 'Computer Services',
    subIndustry: 'Outsourcing',
    size: 'Enterprise',
    location: 'Norwalk, CT',
    globalRevenue: 26039000000,
    ibmSpend: 732008,
    status: 'Active Opportunity',
    lastContact: '2025-06-10',
    installedBase: ['IBM PowerVS'],
    intentScore: 82,
    iscNotes: 'PRICELINE GROUP subsidiary active. KAYAK also in portfolio ($447K). PowerVS discussion around cloud cost optimization. New VP of Cloud Infrastructure hired Q1 2025.',
  },
  {
    id: 'acc-006',
    name: 'SHIFT4 CORPORATION',
    coverageId: 'T0018791',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Services',
    size: 'Enterprise',
    location: 'Allentown, PA',
    globalRevenue: 3335266000,
    ibmSpend: 1132670,
    status: 'Active Opportunity',
    lastContact: '2025-06-19',
    installedBase: ['IBM FlashSystem'],
    intentScore: 88,
    iscNotes: '$1.1M IBM spend. SHIFT4 PAYMENTS LLC subsidiary driving storage refresh. Competitive situation vs. Pure Storage. Champion is Director of Platform Operations.',
  },
  {
    id: 'acc-007',
    name: 'WAWA INC',
    coverageId: 'T0018791',
    industry: 'Retail',
    subIndustry: 'Retail - Retail Food',
    size: 'Enterprise',
    location: 'Wawa, PA',
    globalRevenue: 918067051,
    ibmSpend: 4646086,
    status: 'Active Opportunity',
    lastContact: '2025-06-17',
    installedBase: ['IBM Fusion', 'IBM PowerVS'],
    intentScore: 96,
    iscNotes: '$4.6M IBM spend — highest active engagement in mid-market retail segment. Fusion and PowerVS both deployed. Expansion discussion around real-time analytics for supply chain. CISO relationship established.',
  },
  {
    id: 'acc-008',
    name: 'FIVE BELOW, INC.',
    coverageId: 'T0018791',
    industry: 'Retail',
    subIndustry: 'Retail - Department Stores',
    size: 'Enterprise',
    location: 'Philadelphia, PA',
    globalRevenue: 3876527000,
    ibmSpend: 337489,
    status: 'No Recent Activity',
    lastContact: '2025-02-14',
    installedBase: ['IBM FlashSystem'],
    intentScore: 57,
    iscNotes: 'FlashSystem installed but no active engagement since Q4 2024. Renewal window approaching Q3 2025. New VP of IT confirmed March 2025 — re-engagement opportunity.',
  },
  {
    id: 'acc-009',
    name: 'CLARIVATE',
    coverageId: 'T0018791',
    industry: 'Media & Entertainment',
    subIndustry: 'Printing & Publishing',
    size: 'Enterprise',
    location: 'Philadelphia, PA',
    globalRevenue: 1876894000,
    ibmSpend: 5608085,
    status: 'Active Opportunity',
    lastContact: '2025-06-21',
    installedBase: ['IBM Fusion', 'IBM FlashSystem'],
    intentScore: 93,
    iscNotes: '$5.6M IBM spend. CLARIVATE ANALYTICS active Fusion + FlashSystem deployment. DECISION RESOURCES subsidiary also engaged ($80K). Data intelligence platform expansion in scope.',
  },
  {
    id: 'acc-010',
    name: 'LUTRON ELECTRONICS CO., INC.',
    coverageId: 'T0018791',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Durables',
    size: 'Mid-Market',
    location: 'Coopersburg, PA',
    globalRevenue: 600264312,
    ibmSpend: 1072057,
    status: 'Active Opportunity',
    lastContact: '2025-06-11',
    installedBase: ['IBM PowerVS'],
    intentScore: 79,
    iscNotes: '$1M IBM spend. PowerVS workload running ERP. Conversation around disaster recovery and FlashSystem for on-prem storage tier.',
  },
  {
    id: 'acc-011',
    name: 'PENN NATIONAL GAMING INC',
    coverageId: 'T0018791',
    industry: 'Travel & Transportation',
    subIndustry: 'Lodging',
    size: 'Enterprise',
    location: 'Wyomissing, PA',
    globalRevenue: 6578100000,
    ibmSpend: 625401,
    status: 'No Recent Activity',
    lastContact: '2025-03-05',
    installedBase: ['IBM FlashSystem'],
    intentScore: 60,
    iscNotes: 'Multiple subsidiaries with IBM spend (Plainridge, Ameristar East Chicago, Resorts Casino Hotel). No central engagement. Consolidation play — data center modernization initiative expected H2 2025.',
  },
  {
    id: 'acc-012',
    name: 'IBERDROLA SA',
    coverageId: 'T0018764',
    industry: 'Energy & Utilities',
    subIndustry: 'Electric',
    size: 'Enterprise',
    location: 'Orange, CT',
    globalRevenue: 7184709352,
    ibmSpend: 1855754,
    status: 'Active Opportunity',
    lastContact: '2025-06-16',
    installedBase: ['IBM PowerVS', 'IBM Fusion'],
    intentScore: 86,
    iscNotes: 'IBERDROLA USA MANAGEMENT CORPORATION has $1.8M IBM spend. PowerVS and Fusion in play for grid modernization. UIL HOLDINGS subsidiary also has $43K spend. Strong utility vertical angle.',
  },
  {
    id: 'acc-013',
    name: 'ARTS & ENTERTAINMENT NET',
    coverageId: 'T0018764',
    industry: 'Telecommunications',
    subIndustry: 'Wireline',
    size: 'Enterprise',
    location: 'New York, NY',
    globalRevenue: 91361000000,
    ibmSpend: 436210,
    status: 'No Recent Activity',
    lastContact: '2025-01-20',
    installedBase: ['IBM FlashSystem'],
    intentScore: 52,
    iscNotes: 'A&E TELEVISION NETWORKS has existing FlashSystem install. No recent technical engagement. Content supply chain modernization is a known initiative — Fusion angle worth exploring.',
  },
  {
    id: 'acc-014',
    name: 'TALEN ENERGY CORPORATION',
    coverageId: 'T0018791',
    industry: 'Energy & Utilities',
    subIndustry: 'Electric',
    size: 'Enterprise',
    location: 'Allentown, PA',
    globalRevenue: 37761495664,
    ibmSpend: 636280,
    status: 'Active Opportunity',
    lastContact: '2025-06-08',
    installedBase: ['IBM Fusion'],
    intentScore: 74,
    iscNotes: 'TALEN ENERGY SUPPLY LLC has $632K spend. RAVEN POWER OPERATING also in account hierarchy. Post-bankruptcy restructuring complete — IT modernization budget unlocked. Fusion footprint to be expanded.',
  },
  {
    id: 'acc-015',
    name: 'DIAGEO GRAND MET',
    coverageId: 'T0018764',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Food/Food Svc/Drug',
    size: 'Enterprise',
    location: 'Stamford, CT',
    globalRevenue: 27891000000,
    ibmSpend: 142628,
    status: 'No Recent Activity',
    lastContact: '2025-04-01',
    installedBase: [],
    intentScore: 44,
    iscNotes: 'LIGGETT GROUP subsidiary has $142K IBM spend but very limited footprint. No current IBM infrastructure relationship. New logo opportunity for PowerVS or FlashSystem tied to global SAP S/4 migration.',
  },
  {
    id: 'acc-016',
    name: 'GRUPO BIMBO',
    coverageId: 'T0018791',
    industry: 'Consumer Products',
    subIndustry: 'CP - Food Manufacturing',
    size: 'Enterprise',
    location: 'Horsham, PA',
    globalRevenue: 19767903410,
    ibmSpend: 1930486,
    status: 'Active Opportunity',
    lastContact: '2025-06-13',
    installedBase: ['IBM PowerVS', 'IBM FlashSystem'],
    intentScore: 89,
    iscNotes: 'BIMBO BAKERIES USA INC — $1.9M IBM spend. PowerVS + FlashSystem deployed for SAP environment. Opportunity to expand Fusion for supply chain visibility across North American bakery network.',
  },
  {
    id: 'acc-017',
    name: 'REALOGY CORP',
    coverageId: 'T0018765',
    industry: 'Banking',
    subIndustry: 'Banking - Other',
    size: 'Enterprise',
    location: 'Madison, NJ',
    globalRevenue: 5692000000,
    ibmSpend: 519265,
    status: 'No Recent Activity',
    lastContact: '2025-02-28',
    installedBase: [],
    intentScore: 38,
    iscNotes: 'CARTUS CORPORATION subsidiary has $6.8K spend. REALOGY CORP itself has $512K. Real estate tech consolidation play. No IBM infrastructure currently deployed. Budget cycle Q4.',
  },
  {
    id: 'acc-018',
    name: 'XPO LOGISTICS',
    coverageId: 'T0018764',
    industry: 'Travel & Transportation',
    subIndustry: 'Trucking',
    size: 'Enterprise',
    location: 'Greenwich, CT',
    globalRevenue: 8073325000,
    ibmSpend: 357955,
    status: 'New Logo',
    lastContact: null,
    installedBase: [],
    intentScore: 66,
    iscNotes: 'XPO ENTERPRISE SERVICES LLC has $253K spend. GXO LOGISTICS (spun off) also separately tracked with $180K. Logistics tech modernization — PowerVS for AS/400 workload migration is a strong angle.',
  },
  {
    id: 'acc-019',
    name: 'ASCENA RETAIL GROUP',
    coverageId: 'T0018765',
    industry: 'Retail',
    subIndustry: 'Retail - Specialty',
    size: 'Enterprise',
    location: 'Mahwah, NJ',
    globalRevenue: 1264526175,
    ibmSpend: 1770029,
    status: 'Churned',
    lastContact: '2024-10-15',
    installedBase: [],
    intentScore: 22,
    iscNotes: 'PREMIUM BRANDS SERVICES LLC had $1.7M IBM spend — lost at renewal to cloud-native alternative. Bankruptcy and restructuring impacted budget. Monitor for re-engagement post-stabilization.',
  },
  {
    id: 'acc-020',
    name: 'CHEF\'S WAREHOUSE',
    coverageId: 'T0018764',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Food/Food Svc/Drug',
    size: 'Mid-Market',
    location: 'Ridgefield, CT',
    globalRevenue: 3794212000,
    ibmSpend: 1334482,
    status: 'Active Opportunity',
    lastContact: '2025-06-09',
    installedBase: ['IBM FlashSystem'],
    intentScore: 77,
    iscNotes: 'THE CHEFS WAREHOUSE INC — $1.3M IBM spend. FlashSystem in use for ERP. Growing rapidly via acquisition (14 brands). Opportunity to standardize on IBM storage stack across new acquisitions.',
  },
  {
    id: 'acc-021',
    name: 'GOYA FOODS INC',
    coverageId: 'T0018765',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Food/Food Svc/Drug',
    size: 'Mid-Market',
    location: 'Secaucus, NJ',
    globalRevenue: 349170,
    ibmSpend: 503619,
    status: 'Active Opportunity',
    lastContact: '2025-06-05',
    installedBase: ['IBM PowerVS'],
    intentScore: 71,
    iscNotes: 'Strong IBM relationship relative to revenue. PowerVS active. Family-owned — decision maker is VP of IT. Seasonal demand spikes create infrastructure elasticity need — PowerVS expansion angle.',
  },
  {
    id: 'acc-022',
    name: 'SNCF (GEODIS)',
    coverageId: 'T0018774',
    industry: 'Travel & Transportation',
    subIndustry: 'Freight Services',
    size: 'Enterprise',
    location: 'Piscataway, NJ',
    globalRevenue: 41994050,
    ibmSpend: 9410822,
    status: 'Active Opportunity',
    lastContact: '2025-06-20',
    installedBase: ['IBM Fusion', 'IBM FlashSystem', 'IBM PowerVS'],
    intentScore: 97,
    iscNotes: 'GEODIS GLOBAL SOLUTIONS has $7.1M IBM spend — largest in the territory by spend/revenue ratio. Full IBM stack deployed. Strategic account. Quarterly executive reviews in place. Expansion into AI ops on roadmap.',
  },
  {
    id: 'acc-023',
    name: 'VITAMIN SHOPPE',
    coverageId: 'T0018765',
    industry: 'Retail',
    subIndustry: 'Retail - Retail Food',
    size: 'Mid-Market',
    location: 'Secaucus, NJ',
    globalRevenue: 4397832000,
    ibmSpend: 1912589,
    status: 'No Recent Activity',
    lastContact: '2025-03-18',
    installedBase: ['IBM FlashSystem'],
    intentScore: 55,
    iscNotes: 'VITAMIN SHOPPE INDUSTRIES — $1.9M IBM spend. Part of Franchise Group portfolio. Post-acquisition IT consolidation expected. FlashSystem renewal Q4 2025.',
  },
  {
    id: 'acc-024',
    name: 'ENDURANCE REINSURANCE CORP',
    coverageId: 'T0018764',
    industry: 'Wholesale Distribution & Services',
    subIndustry: 'Wholesale - Services',
    size: 'Enterprise',
    location: 'Stamford, CT',
    globalRevenue: 957154086,
    ibmSpend: 2184440,
    status: 'Active Opportunity',
    lastContact: '2025-06-14',
    installedBase: ['IBM PowerVS', 'IBM Fusion'],
    intentScore: 83,
    iscNotes: 'ENDURANCE SERVICES LTD — $2.1M IBM spend. PowerVS + Fusion for risk analytics workloads. Regulatory compliance driver (NAIC). Sompo Holdings parent creates global expansion opportunity.',
  },
  {
    id: 'acc-025',
    name: 'IMPERIAL BRANDS',
    coverageId: 'T0018765',
    industry: 'Consumer Products',
    subIndustry: 'CP - Beverages & Tobacco',
    size: 'Enterprise',
    location: 'Greensboro, NC',
    globalRevenue: 42888341915,
    ibmSpend: 464862,
    status: 'New Logo',
    lastContact: null,
    installedBase: [],
    intentScore: 61,
    iscNotes: 'ITG BRANDS LLC subsidiary has $464K IBM spend but no infrastructure footprint. Consolidating US operations post-divestiture. Data center rationalization creating infrastructure opportunity window.',
  },
]

export const MOCK_LISTS = [
  {
    id: 'list-001',
    name: 'Motion 1 — High Intent Priority Accounts',
    description: 'RevTech high-scoring accounts for weekly BTSS outbound focus',
    createdAt: '2025-06-01',
    updatedAt: '2025-06-21',
    accountIds: ['acc-007', 'acc-022', 'acc-004', 'acc-009', 'acc-006'],
    color: 'blue',
  },
  {
    id: 'list-002',
    name: 'Q3 Expansion — Existing IBM Footprint',
    description: 'Accounts with $1M+ IBM spend ready for cross-sell / upsell',
    createdAt: '2025-05-20',
    updatedAt: '2025-06-20',
    accountIds: ['acc-002', 'acc-003', 'acc-004', 'acc-016', 'acc-024'],
    color: 'green',
  },
  {
    id: 'list-003',
    name: 'New Logo Targets — Motion 1 Prospecting',
    description: 'Net-new accounts with no IBM infrastructure — whitespace territory',
    createdAt: '2025-06-10',
    updatedAt: '2025-06-18',
    accountIds: ['acc-018', 'acc-025', 'acc-015'],
    color: 'purple',
  },
  {
    id: 'list-004',
    name: 'Re-Engagement — Churned / Inactive',
    description: 'Lost accounts and no-recent-activity targets for Q3 re-engagement cadence',
    createdAt: '2025-06-05',
    updatedAt: '2025-06-12',
    accountIds: ['acc-019', 'acc-008', 'acc-013', 'acc-011', 'acc-017'],
    color: 'orange',
  },
]

// Made with Bob
