// Mock ISC + LinkedIn Sales Navigator signals

export const MOCK_ISC_SIGNALS = [
  {
    id: 'isc-001',
    accountId: 'acc-007',
    accountName: 'WAWA INC',
    type: 'opportunity_update',
    title: 'Q3 Storage Expansion — Stage 3',
    detail: 'Opportunity progressed to Stage 3 (Technical Validation). Customer confirmed budget $1.2M for FlashSystem expansion. Next step: POC sign-off by July 15.',
    date: '2025-06-19',
    owner: 'Sydney Chin',
    priority: 'high',
  },
  {
    id: 'isc-002',
    accountId: 'acc-004',
    accountName: 'CHANEL',
    type: 'activity_logged',
    title: 'Executive briefing completed',
    detail: 'CTO and VP of Digital met with IBM. Confirmed interest in Fusion for global retail data fabric. Follow-up workshop scheduled Aug 5.',
    date: '2025-06-18',
    owner: 'Sydney Chin',
    priority: 'high',
  },
  {
    id: 'isc-003',
    accountId: 'acc-009',
    accountName: 'CLARIVATE',
    type: 'opportunity_update',
    title: 'FlashSystem renewal at risk',
    detail: 'Procurement signaled competitor evaluation (Pure Storage). Price sensitivity flagged. Need competitive positioning doc and updated TCO analysis.',
    date: '2025-06-17',
    owner: 'Sydney Chin',
    priority: 'critical',
  },
  {
    id: 'isc-004',
    accountId: 'acc-022',
    accountName: 'SNCF (GEODIS)',
    type: 'meeting_booked',
    title: 'QBR scheduled — AI ops roadmap',
    detail: 'Quarterly business review with GEODIS Americas CTO. Agenda includes AI ops on IBM stack, Fusion expansion for freight analytics.',
    date: '2025-06-16',
    owner: 'Sydney Chin',
    priority: 'medium',
  },
  {
    id: 'isc-005',
    accountId: 'acc-002',
    accountName: 'CAMPBELL SOUP CO.',
    type: 'new_contact',
    title: 'New IT Director identified',
    detail: 'Sarah Langford joined as Director of IT Infrastructure (formerly at Kraft Heinz). IBM relationship familiar. Warm introduction possible via mutual connection.',
    date: '2025-06-15',
    owner: 'System',
    priority: 'high',
  },
  {
    id: 'isc-006',
    accountId: 'acc-006',
    accountName: 'SHIFT4 CORPORATION',
    type: 'competitive_alert',
    title: 'Pure Storage pitch confirmed',
    detail: 'SE overheard in LinkedIn that Pure Storage SE is engaged with Director of Platform Operations. Opportunity to counter with FlashSystem price-performance data.',
    date: '2025-06-14',
    owner: 'System',
    priority: 'critical',
  },
  {
    id: 'isc-007',
    accountId: 'acc-012',
    accountName: 'IBERDROLA SA',
    type: 'opportunity_update',
    title: 'Grid modernization RFI response submitted',
    detail: 'IBM responded to AVANGRID RENEWABLES RFI. PowerVS + Fusion proposed for real-time grid analytics. Decision expected Q3.',
    date: '2025-06-13',
    owner: 'Sydney Chin',
    priority: 'medium',
  },
  {
    id: 'isc-008',
    accountId: 'acc-016',
    accountName: 'GRUPO BIMBO',
    type: 'activity_logged',
    title: 'Technical discovery call complete',
    detail: 'Mapped SAP HANA workloads to PowerVS. Customer open to Fusion for supply chain visibility. Sizing exercise scheduled.',
    date: '2025-06-12',
    owner: 'Sydney Chin',
    priority: 'medium',
  },
]

export const MOCK_LISN_SIGNALS = [
  {
    id: 'lisn-001',
    accountId: 'acc-007',
    accountName: 'WAWA INC',
    type: 'intent_spike',
    title: 'Intent spike: "enterprise storage modernization"',
    detail: '3 decision-makers at WAWA researching enterprise flash storage topics over the last 7 days. 2 viewed IBM FlashSystem content.',
    date: '2025-06-21',
    intentDelta: +18,
    currentScore: 96,
    topics: ['enterprise flash storage', 'IBM FlashSystem', 'storage TCO'],
  },
  {
    id: 'lisn-002',
    accountId: 'acc-022',
    accountName: 'SNCF (GEODIS)',
    type: 'intent_spike',
    title: 'Intent spike: "AI infrastructure" + "data fabric"',
    detail: '5 contacts at GEODIS Americas engaged with AI infrastructure and data fabric content. CTO profile active on LinkedIn.',
    date: '2025-06-21',
    intentDelta: +12,
    currentScore: 97,
    topics: ['AI infrastructure', 'data fabric', 'supply chain analytics'],
  },
  {
    id: 'lisn-003',
    accountId: 'acc-004',
    accountName: 'CHANEL',
    type: 'job_change',
    title: 'New SVP Technology hired',
    detail: 'Marc Dubois joined as SVP Technology (ex-LVMH). Known IBM advocate. Strong opportunity to re-engage at executive level ahead of FY27 planning.',
    date: '2025-06-20',
    intentDelta: +25,
    currentScore: 94,
    topics: ['executive hire', 'luxury retail tech'],
  },
  {
    id: 'lisn-004',
    accountId: 'acc-009',
    accountName: 'CLARIVATE',
    type: 'intent_spike',
    title: 'Intent spike: "Pure Storage FlashBlade" (competitive)',
    detail: 'IT leadership at Clarivate researching Pure Storage FlashBlade this week. Competitive threat confirmed — counter now.',
    date: '2025-06-20',
    intentDelta: -8,
    currentScore: 93,
    topics: ['Pure Storage', 'FlashBlade', 'storage refresh'],
  },
  {
    id: 'lisn-005',
    accountId: 'acc-003',
    accountName: 'CHURCH & DWIGHT CO INC',
    type: 'job_change',
    title: 'New VP IT Infrastructure hired',
    detail: 'Jennifer Park joined as VP IT Infrastructure. Background in hybrid cloud at P&G. First 90 days — ideal time for discovery conversation.',
    date: '2025-06-19',
    intentDelta: +15,
    currentScore: 85,
    topics: ['executive hire', 'hybrid cloud', 'infrastructure modernization'],
  },
  {
    id: 'lisn-006',
    accountId: 'acc-011',
    accountName: 'PENN NATIONAL GAMING INC',
    type: 'intent_spike',
    title: 'Intent spike: "data center consolidation"',
    detail: '2 IT contacts researching data center consolidation. Post-merger rationalization in progress. Window to position IBM as consolidation platform.',
    date: '2025-06-18',
    intentDelta: +22,
    currentScore: 60,
    topics: ['data center consolidation', 'infrastructure rationalization'],
  },
  {
    id: 'lisn-007',
    accountId: 'acc-005',
    accountName: 'BOOKING HOLDINGS',
    type: 'content_engagement',
    title: 'Director of Platform Eng. engaged with IBM PowerVS content',
    detail: 'Jason Tran, Director of Platform Engineering at Priceline, liked IBM PowerVS migration whitepaper. Strong buying signal.',
    date: '2025-06-17',
    intentDelta: +9,
    currentScore: 82,
    topics: ['IBM PowerVS', 'cloud migration', 'cost optimization'],
  },
  {
    id: 'lisn-008',
    accountId: 'acc-016',
    accountName: 'GRUPO BIMBO',
    type: 'content_engagement',
    title: 'CIO shared IBM SAP on Power case study',
    detail: 'Miguel Hernandez (CIO, Bimbo Bakeries USA) shared IBM\'s SAP on Power case study on LinkedIn with positive commentary.',
    date: '2025-06-16',
    intentDelta: +7,
    currentScore: 89,
    topics: ['SAP on Power', 'IBM PowerVS', 'ERP modernization'],
  },
]

// Mock contacts per account (for SalesLoft / ZoomInfo enrichment flow)
export const MOCK_CONTACTS = {
  'acc-007': [
    { id: 'c-001', name: 'David Kurtz', title: 'VP of IT Infrastructure', email: 'dkurtz@wawa.com', phone: '+1-610-555-0182', linkedin: 'linkedin.com/in/davidkurtz', source: 'ZoomInfo', verified: true },
    { id: 'c-002', name: 'Angela Rossi', title: 'Director of Enterprise Architecture', email: 'arossi@wawa.com', phone: '+1-610-555-0247', linkedin: 'linkedin.com/in/angelarossi', source: 'ZoomInfo', verified: true },
    { id: 'c-003', name: 'Chris Park', title: 'CISO', email: 'cpark@wawa.com', phone: null, linkedin: 'linkedin.com/in/chrispark-wawa', source: 'LinkedIn Sales Navigator', verified: false },
  ],
  'acc-004': [
    { id: 'c-004', name: 'Marc Dubois', title: 'SVP Technology', email: 'mdubois@chanel.com', phone: '+1-212-555-0399', linkedin: 'linkedin.com/in/marcdubois', source: 'LinkedIn Sales Navigator', verified: false },
    { id: 'c-005', name: 'Claire Fontaine', title: 'Director of IT Operations', email: 'cfontaine@chanel.com', phone: '+1-212-555-0412', linkedin: 'linkedin.com/in/clairefontaine-it', source: 'ZoomInfo', verified: true },
  ],
  'acc-022': [
    { id: 'c-006', name: 'Robert Alvarez', title: 'CTO, GEODIS Americas', email: 'ralvarez@geodis.com', phone: '+1-732-555-0101', linkedin: 'linkedin.com/in/robertalvarez-geodis', source: 'ZoomInfo', verified: true },
    { id: 'c-007', name: 'Karen Liu', title: 'VP Technology Solutions', email: 'kliu@geodis.com', phone: '+1-732-555-0178', linkedin: 'linkedin.com/in/karenliu-tech', source: 'ZoomInfo', verified: true },
    { id: 'c-008', name: 'Thomas Bauer', title: 'Head of IT Infrastructure', email: 'tbauer@geodis.com', phone: null, linkedin: 'linkedin.com/in/thomasbauer-logistics', source: 'LinkedIn Sales Navigator', verified: false },
  ],
  'acc-009': [
    { id: 'c-009', name: 'Amanda Walsh', title: 'VP Engineering', email: 'awalsh@clarivate.com', phone: '+1-215-555-0334', linkedin: 'linkedin.com/in/amandawalsh-clarivate', source: 'ZoomInfo', verified: true },
    { id: 'c-010', name: 'Brian Chen', title: 'Director of Infrastructure', email: 'bchen@clarivate.com', phone: '+1-215-555-0291', linkedin: 'linkedin.com/in/brianchen-infra', source: 'ZoomInfo', verified: true },
  ],
  'acc-002': [
    { id: 'c-011', name: 'Sarah Langford', title: 'Director of IT Infrastructure', email: 's.langford@campbellsoup.com', phone: '+1-856-555-0155', linkedin: 'linkedin.com/in/sarahlangford-it', source: 'LinkedIn Sales Navigator', verified: false },
    { id: 'c-012', name: 'George Petrov', title: 'CTO', email: 'g.petrov@campbellsoup.com', phone: '+1-856-555-0199', linkedin: 'linkedin.com/in/georgepetrov', source: 'ZoomInfo', verified: true },
  ],
  'acc-003': [
    { id: 'c-013', name: 'Jennifer Park', title: 'VP IT Infrastructure', email: 'jpark@churchdwight.com', phone: '+1-609-555-0211', linkedin: 'linkedin.com/in/jenniferpark-cdi', source: 'LinkedIn Sales Navigator', verified: false },
    { id: 'c-014', name: 'Michael Torres', title: 'Director of Cloud & Infrastructure', email: 'mtorres@churchdwight.com', phone: '+1-609-555-0244', linkedin: 'linkedin.com/in/michaeltorres-cloud', source: 'ZoomInfo', verified: true },
  ],
}

// Mock SalesLoft cadences for the connection flow
export const MOCK_SALESLOFT_CADENCES = [
  { id: 'sl-4080797', name: 'US | Select | Infrastructure | Outbound | Client-Intro', steps: 7, active: true },
  { id: 'sl-4087855', name: 'US | Select | Infrastructure | Head of IT | Outbound | Fusion | FY26', steps: 8, active: true },
  { id: 'sl-4091234', name: 'US | Select | Storage | FlashSystem | Re-Engagement', steps: 5, active: true },
  { id: 'sl-4095678', name: 'US | Select | Infrastructure | PowerVS | New Logo', steps: 6, active: false },
]

// Made with Bob
